In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import numpy as np
import pandas as pd

import re

import json

In [2]:
# Инициализация драйвера браузера
def initial():
    binary_components_path = 'chrome-win/chrome.exe'

    driver_path = 'chromedriver_win32/chromedriver.exe'

    options = webdriver.ChromeOptions()
    options.binary_location = binary_components_path
    service = Service(driver_path)

    driver = webdriver.Chrome(service=service, options=options)
    return(driver)

In [3]:
# Переход на страницу
def get_page(url):
    driver.get(url)

In [4]:
# Собираем все ссылки на объявления с выбранной страницы
def get_all_links_on_page():
    elements = driver.find_elements(By.CLASS_NAME, value='listing-item__link')

    for element in elements:
        car_list.append(element.get_attribute('href'))
        # print(element.get_attribute('href'), '\n')

    return car_list

In [5]:
# Переход на следующую страницу через нажатие на кнопку
def click_next_page():
    clickable_element = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, '//*[@id="__next"]/div[3]/main/div/div/div[1]/div[4]/div[3]/div/div[4]/div/div[1]/a'))
    )

    clickable_element.click()

In [6]:
# Метод задержки
def waitings():
    # можно ждать explicitly (явно) пока элемент не появится
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, '//*[@id="__next"]/div[3]/main/div/div/div[1]/div[4]/div[3]/div/div[4]/div/div[1]/a'))
    )

In [7]:
def scrapping_car_page():
    details = driver.find_elements(by=By.CLASS_NAME, value='vehicle-form__parameter-item')

    for detail in details:
        
        field_name = detail.find_elements(by=By.CLASS_NAME, value='vehicle-form__parameter-part_1')
        
        field_value = detail.find_elements(by=By.CLASS_NAME, value='vehicle-form__parameter-part_2')

        print(f"field_name: {field_name[0].text}, field_value: {field_value[0].text}")

In [8]:
def parse_car_page():
    driver.get('https://cars.av.by/bmw/x5/104528467')
    mark_model = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[1]/h1')
    print(mark_model[0].text)
    price = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
    car_params = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]')
    car_descr = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[2]')
    car_mod = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[3]/span')
    car_options = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]')

    for pric in price: 
        
        belka = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
        baks = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[2]')
        print(belka[0].text, baks[0].text)

    print(car_params[0].text)
    print(car_descr[0].text)
    print(car_mod[0].text)

    for item in car_options:
        exterior = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[1]')
        security = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[2]')
        pillows = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[3]')
        interior = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[4]')
        helpers = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[5]')
        comfort = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[6]')
        heater = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[7]')
        climat = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[8]')
        multimedia = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[9]')
        faras = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[10]')

    print(exterior[0].text)

In [9]:
# Меняем данные агента
def anonim(version):

    # Инициируем новый драйвер браузера
    driver = initial()

    prop_begin = "Object.defineProperty(navigator, 'userAgent', {value: 'Mozilla/"
    prop_end = ".0 (Windows NT 40.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'});"
    driver.execute_script(prop_begin + str(version) + prop_end)

    return driver

In [10]:
# Создаем список имен колонок
column_names = ['Марка', 'Модель', 'Количество мест', 'Год', 'Место размещения объявления', 'Стоимость BLR', 'Стоимость USD', 
                'Тип коробки передач', 'Объем двигателя', 'Тип двгателя', 'Тип топлива', 'Пробег, км', 'Тип автомобиля', 'Тип привода', 'Цвет автомобиля', 'Мощность двигателя, л/с', 'Расход топлива, л/100 км',]

# Создаем список значений для строки
row_values = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Создаем DataFrame с одной строкой
df = pd.DataFrame([row_values], columns=column_names)

In [ ]:
# Инициируем драйвер браузера
driver = initial()

# вытягиваем список ссылок из csv файла в список
car_list = pd.read_csv('links.csv')
car_list = car_list.values.tolist()
iter = 0

# Начинаем обход всех ссылок списка длиною в вечность
for item in car_list:

    try:

        driver.get(item[0]) # ('https://cars.av.by/bmw/x5/104528467') # 

        if iter % 10 == 0:
            anonim(np.random.randint(5,100))            

        iter += 1
        print(iter, ' item starts')

        link = (item[0])                               # ссылка очень удобная - есть марка машины и модель, отделенные слэшами - хорошо разделяется
        parts = link.split('/')                     # разделяем на элементы. получаем вид: ['https:', '', 'cars.av.by', 'bmw', 'x5', '104528467']
        parts = parts[3:]                           # удаляем первые три элемента     
        parts = parts[:2]                           # удаляем последний
        mark = parts[0]                             # марка машины
        model = parts[1]                            # модель машины


        # Парсим элемент заголовка страницы. В нем содержится марка и модель машины после слова "Продажа", 
        # затем разделитель-запятая и !иногда! присутствует количество мест
        # затем ещё разделитель-запятая и после неё идёт указание года выпуска машины (есть в ещё одном месте на странице) и места размещения объявления
        # из всего интересуте только место размещения объявления и количество мест, если есть
        title = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[1]/h1')
        if title == []:
            title = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[1]/h1')
        title_text = title[0].text
        # Разделение строки на части с использованием запятых в качестве разделителей
        parts = title_text.split(',') # стоит выставить проверку на количество частей - но есть нюанс: имеются заголовки, где модель имеет запятую в названии
        print(parts)
        print(len(parts))
        if len(parts) < 3: # если меньше 3 - значит места не указаны, если 4 и больше - есть запятые в модели
            seats = np.NAN
            parts = parts[-1:] # оставляем только последний элемент: "год. + в месте"
            year_place = parts[0].strip()
            # Разделение строки на части с использованием запятых в качестве разделителей
            parts = year_place.split('.')
            try:
                place = parts[1].strip() # выделяем только место - год возьмём ниже
            except:
                place = np.NAN
        else:
            parts = parts[-2:]
            print(parts)
            seats = parts[0].strip()
            seats = re.sub(r'\D', '', seats) # оставляем только цифру
            print(seats)
            year_place = parts[1].strip()
            # Разделение строки на части с использованием запятых в качестве разделителей
            parts = year_place.split('.')
            try:
                place = parts[1].strip()
            except:
                place = np.NAN

        # Собираем информацию о цене, параметрах, модификации, опциях автомобиля и комментарий продавца
        price = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
        if price == []:
            price = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')

        car_parameters = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]')
        if car_parameters == []:
            car_parameters = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]')
        
        car_descr = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[2]')
        if car_descr == []:
            car_descr = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[2]')

        car_mod = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[3]/span')
        if car_mod == []:
            car_mod = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[3]/span')

        car_options = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]')
        if car_options == []:
            car_options = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]')

        # Работаем с ценником в двух валютах
        for pric in price: 
            
            belka = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
            if belka == []:
                belka = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
            belka = re.sub(r'\D', '', belka[0].text) # оставляем только цифру

            baks = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[2]')
            if baks == []:
                baks = pric.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[2]')
            baks = re.sub(r'\D', '', baks[0].text) # оставляем только цифру
            
        
        # Разделяем по фичам параметры автомобиля
        car_parameters = car_parameters[0].text
        parts = car_parameters.split(',')
        car_parameters_list = []
        for part in parts:
            try:
                car_parameters_list.append(part.strip())
            except:
                car_parameters_list.append(np.NAN)

        # забираем по очереди парметры
        # здесь первым идёт год
        year = car_parameters_list[0].strip()
        year = re.sub(r'\D', '', year) # оставляем только цифру
        kpp_type = car_parameters_list[1].strip()

        if car_parameters_list[2] != np.NAN:
            engine_volume = car_parameters_list[2].strip()
            try:
                engine_volume = re.findall(r'\b\d+(?:\.\d+)?\b', engine_volume) # оставляем только цифру
                engine_volume = float(engine_volume[0])
                engine_type = 'ДВС'
            except:
                engine_volume = np.NAN
                engine_type = 'Электро'
        else: 
            engine_volume = np.NAN
            engine_type = 'Электро'

        fuel_type = car_parameters_list[3].strip()
        mileage = car_parameters_list[4].strip()
        mileage = re.sub(r'\D', '', mileage) # оставляем только цифру 

        # Разделяем по фичам описание автомобиля
        car_descr = car_descr[0].text
        parts = car_descr.split(',')
        
        car_type = parts[0].strip()
        car_drive_type = parts[1].strip()
        car_color = parts[2].strip()

        # Разделяем по фичам модификацию автомобиля
        try:
            car_mod = car_mod[0].text # оказалось, что модификация может и отсутствовать
            parts = car_mod.split(',')
            try:
                engine_power = parts[0].strip()
                engine_power = re.sub(r'\D', '', engine_power) # оставляем только цифру
            except:
                engine_power = np.NAN

            try:
                fuel_consumption = parts[1].strip()
                fuel_consumption = re.findall(r'\b\d+(?:\.\d+)?\b', fuel_consumption) # оставляем только цифру
                fuel_consumption = float(fuel_consumption[0])
            except:
                fuel_consumption = np.NAN
        except:
            engine_power = np.NAN
            fuel_consumption = np.NAN

        print("Марка:", mark)
        print("Модель:", model)
        print("Количество мест:", seats)
        print("Год:", year)
        print("Место объявления:", place)
        print("Стоимость в блр:", belka)
        print("Стоимость в usd:", baks)
        print("Тип коробки передач:", kpp_type)
        print("Объем двигателя, л:", engine_volume)
        print("Тип топлива:", fuel_type)
        print("Пробег, км:", mileage)
        print("Тип автомобиля: ",car_type)
        print("Тип привода: ", car_drive_type)
        print("Цвет автомобиля: ", car_color)
        print("Мощность двигателя, л/с: ", engine_power)
        print("Расход топлива, л/100 км: ", fuel_consumption) 

        for item in car_options:
            exterior = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[1]')
            security = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[2]')
            pillows = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[3]')
            interior = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[4]')
            helpers = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[5]')
            comfort = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[6]')
            heaters = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[7]')
            climat = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[8]')
            multimedia = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[9]')
            faras = item.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[10]')

        """
        print(exterior[0].text)
        print(security[0].text)
        print(pillows[0].text)
        print(interior[0].text)
        print(helpers[0].text)
        print(comfort[0].text)
        print(heater[0].text)
        print(climat[0].text)
        print(multimedia[0].text)
        print(faras[0].text)
        """
        # Обновляем список значений для строки
        row_values = [mark, model, seats, year, place, belka, baks, kpp_type, engine_volume, engine_type, fuel_type, mileage, car_type, car_drive_type, car_color, engine_power, fuel_consumption]
        
        # Добавляем новую строку
        # df = df.append(pd.Series(row_values, index=df.columns), ignore_index=True)
        df.loc[len(df.index)] = row_values
        print('-------------------------------------------------------------')
        print('item added to df')
        print('total number of items in df: ', df.shape[0])
        print('=============================================================')
    
    except:
        print('Something goes wrong...')

df = df.drop_duplicates()
print('Work done')
df

In [18]:
# Инициируем драйвер браузера
driver = initial()

# вытягиваем список ссылок из csv файла в список
car_list = pd.read_csv('links.csv')
car_list = car_list.values.tolist()
iter = 0

# Начинаем обход всех ссылок списка длиною в вечность
for item in car_list:

    try:
        row_values = godness_parse(item[0])

        if iter % 10 == 0:
            anonim(np.random.randint(5,100))  

        df.loc[len(df.index)] = row_values
        print('-------------------------------------------------------------')
        print('item added to df')
        print('total number of items in df: ', df.shape[0])
        print('=============================================================')

        if iter % 100:
            break
    
    except:
        print('Something goes wrong...')

df = df.drop_duplicates()
print('Work done')
df

Марка: opel
Модель: astra
Количество мест: nan
Год: 1994
Место объявления: в Гродно
Стоимость в блр: 1994
Стоимость в usd: 616
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 350000
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  чёрный
Мощность двигателя, л/с:  71
Расход топлива, л/100 км:  6.0
Дополнительные элементы экстерьера: присутствуют
Рейлинги: есть
Системы безопасности: присутствуют
Сигнализация: есть
Подушки безопасности: присутствуют
Передние: есть
Something goes wrong...
Марка: bmw
Модель: 3-seriya
Количество мест: nan
Год: 1985
Место объявления: в Белоозёрске
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 400000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  другой
Мощность двигателя, л/с:  105
Расход топлива, л/100 км:  7.0
Something goes wrong...
Something goes wrong...
Марка: hyundai
Модель: sonata
Количество мест: nan
Год: 1997
Место объявления: в Молодечно
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 2.0
Тип топлива: бензин
Пробег, км: 300000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  зелёный
Мощность двигателя, л/с:  94
Расход топлива, л/100 км:  8.0
Дополнительные элементы экстерьера: присутствуют
Системы безопасности: присутствуют
Something goes wrong...
Марка: toyota
Модель: corolla
Количество мест: nan
Год: 1998
Место объявления: в Минске
Стоимость в блр: 1617
Стоимость в usd: 500
Тип коробки передач: механика
Объем двигателя, л: 2.0
Тип топлива: дизель
Пробег, км: 457000
Тип автомобиля:  лифтбек
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  72
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: присутствуют
Системы безопасности: присутствуют
Подушки безопасности: присутствуют
Something goes wrong...
Марка: mazda
Модель: 323
Количество мест: nan
Год: 2000
Место объявления: в Минске
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 482802
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  114
Расход топлива, л/100 км:  8.0
Дополнительные элементы экстерьера: присутствуют
Диски: есть
Системы безопасности: присутствуют
Подушки безопасности: присутствуют
Something goes wrong...
Something goes wrong...
Марка: bmw
Модель: 3-seriya
Количество мест: nan
Год: 1989
Место объявления: в Белоозёрске
Стоимость в блр: 3073
Стоимость в usd: 950
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 326000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  105
Расход топлива, л/100 км:  7.0
Something goes wrong...
Марка: moskvich
Модель: 412
Количество мест: nan
Год: 1989
Место объявления: в Малорите
Стоимость в блр: 970
Стоимость в usd: 300
Тип коробки передач: механика
Объем двигателя, л: 1.5
Тип топлива: бензин
Пробег, км: 60000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  nan
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Марка: renault
Модель: laguna
Количество мест: nan
Год: 1994
Место объявления: в Витебске
Стоимость в блр: 1941
Стоимость в usd: 600
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 500000
Тип автомобиля:  лифтбек
Тип привода:  передний привод
Цвет автомобиля:  красный
Мощность двигателя, л/с:  90
Расход топлива, л/100 км:  8.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Марка: renault
Модель: clio
Количество мест: nan
Год: 1997
Место объявления: в Бресте
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.4
Тип топлива: бензин
Пробег, км: 200000
Тип автомобиля:  хэтчбек 3 дв.
Тип привода:  передний привод
Цвет автомобиля:  чёрный
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  6.0
Something goes wrong...
Something goes wrong...
Something goes wrong...
Марка: peugeot
Модель: 306
Количество мест: nan
Год: 1997
Место объявления: в Осиповичах
Стоимость в блр: 4529
Стоимость в usd: 1400
Тип коробки передач: механика
Объем двигателя, л: 1.9
Тип топлива: дизель
Пробег, км: 540000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  69
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: присутствуют
Something goes wrong...
Марка: fiat
Модель: brava
Количество мест: nan
Год: 1997
Место объявления: в Мозыре
Стоимость в блр: 3397
Стоимость в usd: 1050
Тип коробки передач: механика
Объем двигателя, л: 1.4
Тип топлива: бензин
Пробег, км: 275000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  7.0
Something goes wrong...
Something goes wrong...
Марка: mazda
Модель: capella
Количество мест: nan
Год: 1986
Место объявления: в Барановичах
Стоимость в блр: 4205
Стоимость в usd: 1300
Тип коробки передач: автомат
Объем двигателя, л: 2.0
Тип топлива: бензин
Пробег, км: 252891
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  145
Расход топлива, л/100 км:  11.0
Something goes wrong...
Марка: mitsubishi
Модель: galant
Количество мест: nan
Год: 1994
Место объявления: в Поставах
Стоимость в блр: 2911
Стоимость в usd: 900
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 350000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  135
Расход топлива, л/100 км:  nan
Something goes wrong...
Something goes wrong...
Марка: nissan
Модель: almera
Количество мест: nan
Год: 1996
Место объявления: в Гродно
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 288000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  зелёный
Мощность двигателя, л/с:  99
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: присутствуют
Фаркоп: есть
Системы безопасности: присутствуют
Something goes wrong...
Марка: volkswagen
Модель: golf
Количество мест: nan
Год: 1995
Место объявления: в Клецке
Стоимость в блр: 3558
Стоимость в usd: 1100
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 385000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Марка: opel
Модель: astra
Количество мест: nan
Год: 1997
Место объявления: в Гомеле
Стоимость в блр: 3238
Стоимость в usd: 1001
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 300088
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  7.0
Something goes wrong...
Марка: fiat
Модель: uno
Количество мест: nan
Год: 1990
Место объявления: в Бресте
Стоимость в блр: 4852
Стоимость в usd: 1500
Тип коробки передач: механика
Объем двигателя, л: 1.4
Тип топлива: бензин
Пробег, км: 242000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  чёрный
Мощность двигателя, л/с:  71
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: присутствуют
Фаркоп: есть
Системы безопасности: присутствуют
Подушки безопасности: присутствуют
Something goes wrong...
Марка: volkswagen
Модель: polo
Количество мест: nan
Год: 1998
Место объявления: в Борисове
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 435421
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  101
Расход топлива, л/100 км:  7.0
Something goes wrong...
Марка: renault
Модель: scenic
Количество мест: nan
Год: 1998
Место объявления: в Жлобине
Стоимость в блр: 2911
Стоимость в usd: 900
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 460000
Тип автомобиля:  минивэн
Тип привода:  передний привод
Цвет автомобиля:  серый
Мощность двигателя, л/с:  90
Расход топлива, л/100 км:  8.0
Дополнительные элементы экстерьера: присутствуют
Системы безопасности: присутствуют
Подушки безопасности: присутствуют
Параметры интерьера: присутствуют
Материал интерьера определен:  Обогрев
Материал интерьера определен:  сидений
Материал интерьера определен:  зеркал
Системы помощи: присутствуют
Дополнительные функции комфорта: присутствуют
Функции обогрева: присутствуют
Функции климата: присутствуют
Something goes wrong...
Марка: lada-vaz
Модель: 21013
Количество мест: nan
Год: 1984
Место объявления: в Осиповичах
Стоимость в блр: 3558
Стоимость в usd: 1100
Тип коробки передач: механика
Объем двигателя, л: 1.2
Тип топлива: бензин
Пробег, км: 86000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  nan
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: lada-vaz
Модель: 2101
Количество мест: nan
Год: 1977
Место объявления: в Барановичах
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.3
Тип топлива: бензин
Пробег, км: 15000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  nan
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: fiat
Модель: brava
Количество мест: nan
Год: 1999
Место объявления: в Минске
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 310000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  103
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Марка: audi
Модель: 100
Количество мест: nan
Год: 1984
Место объявления: в Малорите
Стоимость в блр: 3008
Стоимость в usd: 930
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: дизель
Пробег, км: 352332
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  жёлтый
Мощность двигателя, л/с:  0
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: ford
Модель: escort
Количество мест: nan
Год: 1997
Место объявления: в Кобрине
Стоимость в блр: 1003
Стоимость в usd: 310
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 50000
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  105
Расход топлива, л/100 км:  8.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Марка: renault
Модель: laguna
Количество мест: nan
Год: 1993
Место объявления: в Ивацевичах
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 2.2
Тип топлива: дизель
Пробег, км: 450000
Тип автомобиля:  лифтбек
Тип привода:  передний привод
Цвет автомобиля:  зелёный
Мощность двигателя, л/с:  83
Расход топлива, л/100 км:  6.0
Something goes wrong...
Марка: renault
Модель: trafic
Количество мест: nan
Год: 1996
Место объявления: в Витебске
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 2.5
Тип топлива: дизель
Пробег, км: 300000
Тип автомобиля:  микроавтобус пассажирский
Тип привода:  передний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  72
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: zaz
Модель: 968
Количество мест: nan
Год: 1987
Место объявления: в Гомеле
Стоимость в блр: 1500
Стоимость в usd: 464
Тип коробки передач: механика
Объем двигателя, л: 1.2
Тип топлива: бензин
Пробег, км: 90000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  42
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Марка: gaz
Модель: 31105
Количество мест: nan
Год: 2005
Место объявления: в Могилеве
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 2.3
Тип топлива: бензин (пропан-бутан)
Пробег, км: 418000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  зелёный
Мощность двигателя, л/с:  nan
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: присутствуют
Диски: есть
Системы безопасности: присутствуют
Подушки безопасности: присутствуют
Something goes wrong...
Something goes wrong...
Марка: hyundai
Модель: lantra
Количество мест: nan
Год: 1996
Место объявления: в Минске
Стоимость в блр: 1779
Стоимость в usd: 550
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 396097
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  красный
Мощность двигателя, л/с:  114
Расход топлива, л/100 км:  8.0
Something goes wrong...
Марка: citroen
Модель: xantia
Количество мест: nan
Год: 1999
Место объявления: в Минске
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 2.0
Тип топлива: дизель
Пробег, км: 333333
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  красный
Мощность двигателя, л/с:  109
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: mazda
Модель: 323
Количество мест: nan
Год: 1994
Место объявления: в Полоцке
Стоимость в блр: 1553
Стоимость в usd: 480
Тип коробки передач: механика
Объем двигателя, л: 1.3
Тип топлива: бензин
Пробег, км: 330000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  красный
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Something goes wrong...
Марка: nissan
Модель: maxima
Количество мест: nan
Год: 1995
Место объявления: в Могилеве
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 2.0
Тип топлива: бензин
Пробег, км: 350000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  140
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: volkswagen
Модель: passat
Количество мест: nan
Год: 1989
Место объявления: в Гомеле
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 350000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  другой
Мощность двигателя, л/с:  75
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: fiat
Модель: brava
Количество мест: nan
Год: 1997
Место объявления: в Сенно
Стоимость в блр: 4205
Стоимость в usd: 1300
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 187743
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  серый
Мощность двигателя, л/с:  103
Расход топлива, л/100 км:  7.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Марка: volkswagen
Модель: passat
Количество мест: nan
Год: 1986
Место объявления: в Солигорске
Стоимость в блр: 3882
Стоимость в usd: 1200
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: дизель
Пробег, км: 666666
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  красный
Мощность двигателя, л/с:  70
Расход топлива, л/100 км:  6.0
Something goes wrong...
Something goes wrong...
Марка: renault
Модель: safrane
Количество мест: nan
Год: 1995
Место объявления: в Ракове
Стоимость в блр: 1941
Стоимость в usd: 600
Тип коробки передач: механика
Объем двигателя, л: 2.1
Тип топлива: дизель
Пробег, км: 490000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  90
Расход топлива, л/100 км:  nan
Something goes wrong...
Марка: volvo
Модель: 740
Количество мест: nan
Год: 1988
Место объявления: в Витебске
Стоимость в блр: 2588
Стоимость в usd: 800
Тип коробки передач: механика
Объем двигателя, л: 2.3
Тип топлива: бензин
Пробег, км: 230000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  серебристый
Мощность двигателя, л/с:  nan
Расход топлива, л/100 км:  nan
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Марка: lada-vaz
Модель: 2106
Количество мест: nan
Год: 1996
Место объявления: в Климовичах
Стоимость в блр: 3558
Стоимость в usd: 1100
Тип коробки передач: механика
Объем двигателя, л: 1.6
Тип топлива: бензин
Пробег, км: 76000
Тип автомобиля:  седан
Тип привода:  задний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  74
Расход топлива, л/100 км:  10.0
Something goes wrong...
Марка: hyundai
Модель: accent
Количество мест: nan
Год: 1996
Место объявления: в Малорите
Стоимость в блр: 2103
Стоимость в usd: 650
Тип коробки передач: механика
Объем двигателя, л: 1.3
Тип топлива: бензин
Пробег, км: 222222
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  другой
Мощность двигателя, л/с:  60
Расход топлива, л/100 км:  6.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Марка: renault
Модель: clio
Количество мест: nan
Год: 1991
Место объявления: в Малорите
Стоимость в блр: 2588
Стоимость в usd: 800
Тип коробки передач: механика
Объем двигателя, л: 1.4
Тип топлива: бензин
Пробег, км: 300000
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  синий
Мощность двигателя, л/с:  80
Расход топлива, л/100 км:  6.0
Something goes wrong...
Something goes wrong...
Марка: kia
Модель: clarus
Количество мест: nan
Год: 1998
Место объявления: в Руденске
Стоимость в блр: 3235
Стоимость в usd: 1000
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 340450
Тип автомобиля:  универсал
Тип привода:  передний привод
Цвет автомобиля:  другой
Мощность двигателя, л/с:  114
Расход топлива, л/100 км:  9.0
Дополнительные элементы экстерьера: отсутствуют
Системы безопасности: отсутствуют
Подушки безопасности: отсутствуют
Something goes wrong...
Something goes wrong...
Марка: ford
Модель: mondeo
Количество мест: nan
Год: 1995
Место объявления: в Докшицах
Стоимость в блр: 3397
Стоимость в usd: 1050
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин
Пробег, км: 250000
Тип автомобиля:  седан
Тип привода:  передний привод
Цвет автомобиля:  зелёный
Мощность двигателя, л/с:  116
Расход топлива, л/100 км:  7.0
Something goes wrong...
Марка: fiat
Модель: punto
Количество мест: nan
Год: 1998
Место объявления: в Борисове
Стоимость в блр: 1617
Стоимость в usd: 500
Тип коробки передач: механика
Объем двигателя, л: 1.2
Тип топлива: бензин
Пробег, км: 278525
Тип автомобиля:  хэтчбек 5 дв.
Тип привода:  передний привод
Цвет автомобиля:  белый
Мощность двигателя, л/с:  86
Расход топлива, л/100 км:  6.0
Something goes wrong...
Something goes wrong...
Марка: ford
Модель: mondeo
Количество мест: nan
Год: 1998
Место объявления: в Минске
Стоимость в блр: 1909
Стоимость в usd: 590
Тип коробки передач: механика
Объем двигателя, л: 1.8
Тип топлива: бензин

,Марка,Модель,Количество мест,Год,Место размещения объявления,Стоимость BLR,Стоимость USD,Тип коробки передач,Объем двигателя,Тип топлива,...,Опции мультимедиа,AUX или iPod,Bluetooth,CD или MP3,Мультимедийный экран,Штатная навигация,Опции фар,Фары ксеноновые,Фары противотуманные,Фары светодиодные
0,bmw,x5,5,2019,в Барановичах,202175,62500,автомат,3.0,дизель,...,1,1,1,1,1,1,1,1,1,1

In [11]:
# необходимо сохранять прогресс парсинга в специальный файл json

def save_progress_json(iter):
    # Переменная для записи в файл JSON
    data_to_write = {
        "iteration": iter
    }

    # Путь к файлу JSON
    file_path = "iter.json"

    # Запись переменной в файл JSON
    with open(file_path, "w") as json_file:
        json.dump(data_to_write, json_file, indent=4)

    print("Данные успешно записаны в файл JSON:", file_path)

In [12]:
df.shape[0]

1

In [41]:
print(df.info())
df.to_csv('cars.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 1054 entries, 0 to 1053
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Марка                        1054 non-null   object
 1   Модель                       1054 non-null   object
 2   Количество мест              27 non-null     object
 3   Год                          1054 non-null   object
 4   Место размещения объявления  1054 non-null   object
 5   Стоимость BLR                1054 non-null   object
 6   Стоимость USD                1054 non-null   object
 7   Тип коробки передач          1054 non-null   object
 8   Объем двигателя              1054 non-null   float64
 9   Тип двгателя                 1054 non-null   object
 10  Тип топлива                  1054 non-null   object
 11  Пробег, км                   1054 non-null   object
 12  Тип автомобиля               1054 non-null   object
 13  Тип привода                  1054 non-null   object
 14  Цвет автомобиля              1054 non-null   object
 15  Мощность двигателя, л/с      906 non-null    object
 16  Расход топлива, л/100 км     735 non-null    float64
dtypes: float64(2), object(15)
memory usage: 148.2+ KB
None

при фильтре от 50000$ результатов: ~2562
от 40к до 50к: ~1847
от 35к до 40к: ~1952
от 30к до 35к: ~2612
далее - надоело. нужно автоматизировать

In [13]:
def choosing_diapasons(min, url_min, url_max, min_max_scale):
    print("pool started")
    for i in range (100, 64500, 100):
        full_url = url_min + str(min) + url_max + str(min + i)
        get_page(full_url)
        number_of_items = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[3]/form/div/div[3]/div/div[3]/div[2]/div[2]/button/span')
        number_of_items = number_of_items[0].text
        print(number_of_items)
        number_of_items = re.findall(r'\d+', number_of_items)
        number_of_items = int(''.join(number_of_items))
        print(number_of_items)
        min_max = [min, min + i]
        if number_of_items >= 3000:
            break
    print("pool added")
    print(min_max)
    min_max_scale.append(min_max)
    min += i

In [17]:
# Найдем нужные диапазоны цен (не более 3000 машин или 120 страниц в каждом)
url_min = "https://cars.av.by/filter?price_usd[min]="
url_max = "&price_usd[max]="
min_max_scale = []
min = 0

while True:
    choosing_diapasons(min, url_min, url_max, min_max_scale)

pool started
Показать 1 объявление
1
Показать 17 объявлений
17
Показать 88 объявлений
88

KeyboardInterrupt:

In [ ]:
for pare in min_max_scale:
    print(pare[0])

In [15]:

# https://cars.av.by/filter?price_usd[max]=1000&page=2
# https://cars.av.by/filter?price_usd[min]=1000&price_usd[max]=1500&page=2

car_list = []
url_min = "https://cars.av.by/filter?price_usd[min]="
url_max = "&price_usd[max]="

# Инициируем драйвер браузера
driver = initial()

# Пройдём по всем диапазонам
for pare in min_max_scale:
    full_url = url_min + str(pare[0]) + url_max + str(pare[1])
    # Пройдём по всем 120 страницам и соберем ссылки на машины
    for i in range (1,125):
        try:
            get_page(full_url + "&page=" + str(i))
            print("Page: ", i)
            print(full_url + "&page=" + str(i))
            car_list = get_all_links_on_page()
        except:
            break


len(car_list)

NameError: name 'min_max_scale' is not defined

выяснилось, что на 120 странице av.by ломается. как вариант - использовать ограничения по ценнику с шагом в 500 бачей - получается от 1500 до 3000 элементов за раз. при таком количестве вроде не должно сломаться

In [88]:
unique_car_list = []
[unique_car_list.append(x) for x in car_list if x not in unique_car_list]
unique_car_list = pd.DataFrame(unique_car_list, columns=['Link'])
unique_car_list.to_csv('links.csv', index=False)

In [89]:
len(unique_car_list)

48887

In [13]:
# Создаем список имен колонок
column_names = ['Марка', 'Модель', 'Количество мест', 'Год', 'Место размещения объявления', 'Стоимость BLR', 'Стоимость USD', 
                'Тип коробки передач', 'Объем двигателя', 'Тип топлива', 'Пробег, км', 'Тип автомобиля', 'Тип привода', 'Цвет автомобиля', 'Мощность двигателя, л/с', 'Расход топлива, л/100 км',]

# Создаем список значений для строки
row_values = [mark, model, seats, year, place, belka, baks, kpp_type, engine_volume, fuel_type, mileage, car_type, car_drive_type, car_color, engine_power, fuel_consumption]

# Создаем DataFrame с одной строкой
df = pd.DataFrame([row_values], columns=column_names)
df

,Марка,Модель,Количество мест,Год,Место размещения объявления,Стоимость BLR,Стоимость USD,Тип коробки передач,Объем двигателя,Тип топлива,"Пробег, км",Тип автомобиля,Тип привода,Цвет автомобиля,"Мощность двигателя, л/с","Расход топлива, л/100 км"
0,BMW,X5 G05,5,2019,в Барановичах,202084,62800,автомат,3.0,дизель,115000,внедорожник 5 дв.,постоянный полный привод,чёрный,265,6.0

In [ ]:
# Добавляем новую строку
df = df.append(pd.Series(row_values, index=df.columns), ignore_index=True)

In [52]:
driver.quit()

In [47]:
df

,Марка,Модель,Количество мест,Год,Место размещения объявления,Стоимость BLR,Стоимость USD,Тип коробки передач,Объем двигателя,Тип двгателя,Тип топлива,"Пробег, км",Тип автомобиля,Тип привода,Цвет автомобиля,"Мощность двигателя, л/с","Расход топлива, л/100 км"
0,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0.0
1,Skoda,Rapid I · Рестайлинг,0,2018,в Молодечно,51000,15895,2018 г.,NaN,Электро,1.6 л,,лифтбек,передний привод,зелёный,110,6.0
2,Honda,Accord X,0,2020,в Минске,72191,22500,2020 г.,NaN,Электро,1.5 л,,седан,передний привод,серый,192,7.0
3,Lada,(ВАЗ) Granta I · Рестайлинг,0,2020,в Могилеве,28556,8900,2020 г.,NaN,Электро,1.6 л,,лифтбек,передний привод,красный,106,6.0
4,Citroen,C4 Grand Picasso I,0,7,NaN,30962,9650,2009 г.,NaN,Электро,1.6 л,,минивэн,передний привод,серый,112,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Ford,Mondeo III · Рестайлинг,0,2006,в Дзержинске,16043,5000,2006 г.,NaN,Электро,1.8 л,,седан,передний привод,другой,125,7.0
98,BMW,X5 G05,0,5,NaN,239996,74800,2019 г.,NaN,Электро,3.0 л,,внедорожник 5 дв.,постоянный полный привод,серый,265,6.0
99,Mercedes-Benz,CLA II,0,2019,в Минске,86469,26950,2019 г.,NaN,Электро,1.3 л,,универсал,передний привод,серый,163,5.0
100,Volkswagen,Polo Sedan I,0,2014,в Барановичах,28716,8950,2014 г.,NaN,Электро,1.6 л,,седан,передний привод,серебристый,105,6.0
101,Skoda,Octavia II · Рестайлинг,0,2013,в Минске,25187,7850,2013 г.,NaN,Электро,1.6 л,,лифтбек,передний привод,другой,102,7.0

Полностью работа по элементам страницы здесь

In [10]:
# Инициируем драйвер браузера
driver = initial()

In [14]:
url = 'https://cars.av.by/bmw/x5/104528467'
godness_parse(url)

Марка: bmw
Модель: x5
Количество мест: 5
Год: 2019
Место объявления: в Барановичах
Стоимость в блр: 202175
Стоимость в usd: 62500
Тип коробки передач: автомат
Объем двигателя, л: 3.0
Тип топлива: дизель
Пробег, км: 115000
Тип автомобиля:  внедорожник 5 дв.
Тип привода:  постоянный полный привод
Цвет автомобиля:  чёрный
Мощность двигателя, л/с:  265
Расход топлива, л/100 км:  6.0
Дополнительные элементы экстерьера: присутствуют
Диски: есть
Рейлинги: есть
Системы безопасности: присутствуют
ABS: есть
ESP: есть
Антипробуксовочная: есть
Сигнализация: есть
Подушки безопасности: присутствуют
Передние: есть
Боковые: есть
Задние: есть
Параметры интерьера: присутствуют
Цвет интерьера определен:  тёмный
Материал интерьера определен:  натуральная кожа
Панорамная крыша: есть
Системы помощи: присутствуют
Датчик дождя: есть
Камера заднего вида: есть
Парктроники: есть
Дополнительные функции комфорта: присутствуют
Круиз-контроль: есть
Управление мультимедиа с руля: есть
Электрорегулировка сидений: есть
Передние электро-стеклоподъёмники: есть
Задние электро-стеклоподъёмники: есть
Функции обогрева: присутствуют
Обогрев сидений: есть
Обогрев лобового стекла: есть
Обогрев зеркал: есть
Обогрев руля: есть
Автономный отопитель: есть
Функции климата: присутствуют
Климат-контроль: есть
Опции мультимедиа: присутствуют
AUX или iPod: есть
Bluetooth: есть
CD или MP3: есть
USB: есть
Мультимедийный экран: есть
Штатная навигация: есть
Опции фар: присутствуют
Фары ксеноновые: есть
Фары противотуманные: есть
Фары светодиодные: есть
-------------------------------------------------------------
=============================================================

In [17]:
def godness_parse(url):
        
    driver.get(url)                      # ('https://cars.av.by/bmw/x5/104528467')  # (item[0]) # 

    link = (url)  # ссылка очень удобная - есть марка машины и модель, отделенные слэшами - хорошо разделяется
    parts = link.split('/')  # разделяем на элементы. получаем вид: ['https:', '', 'cars.av.by', 'bmw', 'x5', '104528467']
    parts = parts[3:]  # удаляем первые три элемента     
    parts = parts[:2]  # удаляем последний
    mark = parts[0]  # марка машины
    model = parts[1]  # модель машины

    # Парсим элемент заголовка страницы. В нем содержится марка и модель машины после слова "Продажа", 
    # затем разделитель-запятая и !иногда! присутствует количество мест
    # затем ещё разделитель-запятая и после неё идёт указание года выпуска машины (есть в ещё одном месте на странице) и места размещения объявления
    # из всего интересуте только место размещения объявления и количество мест, если есть
    title = driver.find_elements(by=By.XPATH, value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[1]/h1')
    if title == []:
        title = driver.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[1]/h1')
    title_text = title[0].text
    # Разделение строки на части с использованием запятых в качестве разделителей
    parts = title_text.split(
        ',')  # стоит выставить проверку на количество частей - но есть нюанс: имеются заголовки, где модель имеет запятую в названии
    # print(parts)
    # print(len(parts))
    if len(parts) < 3:  # если меньше 3 - значит места не указаны, если 4 и больше - есть запятые в модели
        seats = np.NAN
        parts = parts[-1:]  # оставляем только последний элемент: "год. + в месте"
        year_place = parts[0].strip()
        # Разделение строки на части с использованием запятых в качестве разделителей
        parts = year_place.split('.')
        try:
            place = parts[1].strip()  # выделяем только место - год возьмём ниже
        except:
            place = np.NAN
    else:
        parts = parts[-2:]
        # print(parts)
        seats = parts[0].strip()
        seats = re.sub(r'\D', '', seats)  # оставляем только цифру
        # print(seats)
        year_place = parts[1].strip()
        # Разделение строки на части с использованием запятых в качестве разделителей
        parts = year_place.split('.')
        try:
            place = parts[1].strip()
        except:
            place = np.NAN

    # Собираем информацию о цене, параметрах, модификации, опциях автомобиля и комментарий продавца
    price = driver.find_elements(by=By.XPATH,
                                value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
    if price == []:
        price = driver.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')

    car_parameters = driver.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]')
    if car_parameters == []:
        car_parameters = driver.find_elements(by=By.XPATH,
                                            value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]')

    car_descr = driver.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[2]')
    if car_descr == []:
        car_descr = driver.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[2]')

    car_mod = driver.find_elements(by=By.XPATH,
                                value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[3]/span')
    if car_mod == []:
        car_mod = driver.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[3]/span')

    car_options = driver.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]')
    if car_options == []:
        car_options = driver.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]')

    # Работаем с ценником в двух валютах
    for pric in price:

        belka = pric.find_elements(by=By.XPATH,
                                value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
        if belka == []:
            belka = pric.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[1]')
        belka = re.sub(r'\D', '', belka[0].text)  # оставляем только цифру

        baks = pric.find_elements(by=By.XPATH,
                                value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[2]')
        if baks == []:
            baks = pric.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div/div[2]')
        baks = re.sub(r'\D', '', baks[0].text)  # оставляем только цифру

    # Разделяем по фичам параметры автомобиля
    car_parameters = car_parameters[0].text
    parts = car_parameters.split(',')
    car_parameters_list = []
    for part in parts:
        try:
            car_parameters_list.append(part.strip())
        except:
            car_parameters_list.append(np.NAN)

    # забираем по очереди парметры
    # здесь первым идёт год
    year = car_parameters_list[0].strip()
    year = re.sub(r'\D', '', year)  # оставляем только цифру
    kpp_type = car_parameters_list[1].strip()

    if car_parameters_list[2] != np.NAN:
        engine_volume = car_parameters_list[2].strip()
        try:
            engine_volume = re.findall(r'\b\d+(?:\.\d+)?\b', engine_volume)  # оставляем только цифру
            engine_volume = float(engine_volume[0])
            engine_type = 'ДВС'
        except:
            engine_volume = np.NAN
            engine_type = 'Электро'
    else:
        engine_volume = np.NAN
        engine_type = 'Электро'

    fuel_type = car_parameters_list[3].strip()
    mileage = car_parameters_list[4].strip()
    mileage = re.sub(r'\D', '', mileage)  # оставляем только цифру 

    # Разделяем по фичам описание автомобиля
    car_descr = car_descr[0].text
    parts = car_descr.split(',')

    car_type = parts[0].strip()
    car_drive_type = parts[1].strip()
    car_color = parts[2].strip()

    # Разделяем по фичам модификацию автомобиля
    try:
        car_mod = car_mod[0].text  # оказалось, что модификация может и отсутствовать
        parts = car_mod.split(',')
        try:
            engine_power = parts[0].strip()
            engine_power = re.sub(r'\D', '', engine_power)  # оставляем только цифру
        except:
            engine_power = np.NAN

        try:
            fuel_consumption = parts[1].strip()
            fuel_consumption = re.findall(r'\b\d+(?:\.\d+)?\b', fuel_consumption)  # оставляем только цифру
            fuel_consumption = float(fuel_consumption[0])
        except:
            fuel_consumption = np.NAN
    except:
        engine_power = np.NAN
        fuel_consumption = np.NAN

    print("Марка:", mark)
    print("Модель:", model)
    print("Количество мест:", seats)
    print("Год:", year)
    print("Место объявления:", place)
    print("Стоимость в блр:", belka)
    print("Стоимость в usd:", baks)
    print("Тип коробки передач:", kpp_type)
    print("Объем двигателя, л:", engine_volume)
    print("Тип топлива:", fuel_type)
    print("Пробег, км:", mileage)
    print("Тип автомобиля: ", car_type)
    print("Тип привода: ", car_drive_type)
    print("Цвет автомобиля: ", car_color)
    print("Мощность двигателя, л/с: ", engine_power)
    print("Расход топлива, л/100 км: ", fuel_consumption)

    for item in car_options:
        exterior = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[1]')
        if exterior == []:
            exterior = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[1]')

        security = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[2]')
        if security == []:
            security = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[2]')

        pillows = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[3]')
        if pillows == []:
            pillows = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[3]')

        helpers = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[4]')
        if helpers == []:
            helpers = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[4]')

        interior = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[5]')
        if interior == []:
            interior = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[5]')

        comfort = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[6]')
        if comfort == []:
            comfort = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[6]')

        heaters = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[7]')
        if heaters == []:
            heaters = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[7]')

        climat = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[8]')
        if climat == []:
            climat = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[8]')

        multimedia = item.find_elements(by=By.XPATH,
                                        value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[9]')
        if multimedia == []:
            multimedia = item.find_elements(by=By.XPATH,
                                            value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[9]')

        faras = item.find_elements(by=By.XPATH,
                                value='//*[@id="__next"]/div[3]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[10]')
        if faras == []:
            faras = item.find_elements(by=By.XPATH,
                                    value='//*[@id="__next"]/div[2]/main/div/div/div[1]/div[1]/div[3]/div[7]/div/div[10]')

    # Разбираемся с экстерьером
    # print(exterior[0].text )
    exterior = exterior[0].text  # этот пункт содержит в себе строку с разделителями /n
    parts = exterior.split('\n')  # разделяем строку в список
    # print(parts)
    disks = np.NaN
    reiling = np.NaN
    farkop = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        exterior = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Дополнительные элементы экстерьера: присутствуют')

        for item in parts:
            if 'диски' in item:
                disks = 1
                print('Диски: есть')

            elif 'рейлинг' in item:
                reiling = 1
                print('Рейлинги: есть')

            elif 'фаркоп' in item:
                farkop = 1
                print('Фаркоп: есть')

    else:
        exterior = 0
        print('Дополнительные элементы экстерьера: отсутствуют')

    # Разбираемся с системами безопасности
    security = security[0].text  # этот пункт содержит в себе строку с разделителями /n
    parts = security.split('\n')
    # print(parts)
    abs = np.NaN
    esp = np.NaN
    antibuks = np.NaN
    immobilaizer = np.NaN
    alarm = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        security = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Системы безопасности: присутствуют')

        for item in parts:
            if 'ABS' in item:
                abs = 1
                print('ABS: есть')

            if 'ESP' in item:
                esp = 1
                print('ESP: есть')

            if 'антипробуксовочная' in item:
                antibuks = 1
                print('Антипробуксовочная: есть')

            if 'иммобилайзер' in item:
                immobilaizer = 1
                print('Иммобилайзер: есть')

            if 'сигнализация' in item:
                alarm = 1
                print('Сигнализация: есть')

    else:
        security = 0
        print('Системы безопасности: отсутствуют')

    # Разбираемся с системами безопасности
    pillows = pillows[0].text
    parts = pillows.split('\n')
    # print(parts)
    front = np.NaN
    back = np.NaN
    side = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        pillows = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Подушки безопасности: присутствуют')

        for item in parts:
            if 'передние' in item:
                front = 1
                print('Передние: есть')

            if 'задние' in item:
                back = 1
                print('Задние: есть')

            if 'боковые' in item:
                side = 1
                print('Боковые: есть')

    else:
        pillows = 0
        print('Подушки безопасности: отсутствуют')

    # Разбираемся с системами безопасности
    interior = interior[0].text
    parts = interior.split('\n')
    # print(parts)

    # Решил сразу выставить все наны. Что будет в наличии - изменю на значения.
    vehicle_interior_color = np.NAN
    vehicle_interior_material = np.NaN
    panorama_roof = np.NaN
    car_sunroof = np.NaN
    sevenseats_version = np.NAN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        interior = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Параметры интерьера: присутствуют')

        for item in parts:
            if 'панорамная крыша' in item:
                panorama_roof = 1
                print('Панорамная крыша: есть')

            elif 'люк' in item:
                car_sunroof = 1
                print('Люк: есть')

            elif '7 местная' in item:
                sevenseats_version = 1
                print('Боковые: есть')

            elif 'светлый' in item:
                vehicle_interior_color = item
                print('Цвет интерьера определен: ', item)
            elif 'тёмный' in item:
                vehicle_interior_color = item
                print('Цвет интерьера определен: ', item)
            elif 'комби' in item:
                vehicle_interior_color = item
                print('Цвет интерьера определен: ', item)
            elif 'Интерьер' in item:
                pass

            else:
                vehicle_interior_material = item
                print('Материал интерьера определен: ', item)

    else:
        interior = 0
        print('Параметры интерьера: отсутствуют')

    # Разбираемся с системами помощи
    helpers = helpers[0].text
    parts = helpers.split('\n')
    # print(parts)
    rain_sensor = np.NAN
    backview_camera = np.NaN
    parktroniks = np.NaN
    mirror_deathzones_control = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        helpers = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Системы помощи: присутствуют')

        for item in parts:
            if 'датчик дождя' in item:
                rain_sensor = 1
                print('Датчик дождя: есть')

            if 'камера заднего вида' in item:
                backview_camera = 1
                print('Камера заднего вида: есть')

            if 'парктроники' in item:
                parktroniks = 1
                print('Парктроники: есть')

            if 'контроль мертвых зон на зеркалах' in item:
                mirror_deathzones_control = 1
                print('Контроль мертвых зон на зеркалах: есть')


    else:
        helpers = 0
        print('Системы помощи: отсутствуют')

    # Разбираемся с функциями комфорта
    comfort = comfort[0].text
    parts = comfort.split('\n')
    # print(parts)
    engine_autostart = np.NaN
    cruise_control = np.NaN
    mediacontrol_from_steering_wheel = np.NaN
    electrically_adjustable_seats = np.NaN
    front_electric_window_regulator = np.NaN
    back_electric_window_regulator = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        comfort = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Дополнительные функции комфорта: присутствуют')

        for item in parts:
            if 'Автозапуск двигателя' in item:
                engine_autostart = 1
                print('Автозапуск двигателя: есть')

            if 'круиз-контроль' in item:
                cruise_control = 1
                print('Круиз-контроль: есть')

            if 'управление мультимедиа с руля' in item:
                mediacontrol_from_steering_wheel = 1
                print('Управление мультимедиа с руля: есть')

            if 'электрорегулировка сидений' in item:
                electrically_adjustable_seats = 1
                print('Электрорегулировка сидений: есть')

            if 'передние электро-стеклоподъёмники' in item:
                front_electric_window_regulator = 1
                print('Передние электро-стеклоподъёмники: есть')

            if 'задние электро-стеклоподъёмники' in item:
                back_electric_window_regulator = 1
                print('Задние электро-стеклоподъёмники: есть')

    else:
        comfort = 0
        print('Дополнительные функции комфорта: отсутствуют')

    # Разбираемся с функциями обогрева
    heaters = heaters[0].text
    parts = heaters.split('\n')
    # print(parts)
    seats_heating = np.NaN
    windshield_heating = np.NaN
    mirrors_heating = np.NaN
    steering_wheel_heating = np.NaN
    heater = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        heaters = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Функции обогрева: присутствуют')

        for item in parts:
            if 'сидений' in item:
                seats_heating = 1
                print('Обогрев сидений: есть')

            if 'лобового стекла' in item:
                windshield_heating = 1
                print('Обогрев лобового стекла: есть')

            if 'зеркал' in item:
                mirrors_heating = 1
                print('Обогрев зеркал: есть')

            if 'руля' in item:
                steering_wheel_heating = 1
                print('Обогрев руля: есть')

            if 'автономный отопитель' in item:
                heater = 1
                print('Автономный отопитель: есть')

    else:
        heaters = 0
        print('Функции обогрева: отсутствуют')

    # Разбираемся с функциями климата
    climat = climat[0].text
    parts = climat.split('\n')
    # print(parts)
    climat_control = np.NaN
    condition = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        climat = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Функции климата: присутствуют')

        for item in parts:
            if 'климат-контроль' in item:
                climat_control = 1
                print('Климат-контроль: есть')

            if 'кондиционер' in item:
                condition = 1
                print('Кондиционер: есть')

    else:
        climat = 0
        print('Функции климата: отсутствуют')

    # Разбираемся с функциями климата
    multimedia = multimedia[0].text
    parts = multimedia.split('\n')
    # print(parts)
    aux_ipod = np.NaN
    bluetooth = np.NaN
    cd_mp3 = np.NaN
    usb = np.NaN
    multimedia_monitor = np.NaN
    factory_navigation = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        multimedia = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Опции мультимедиа: присутствуют')

        for item in parts:
            if 'AUX или iPod' in item:
                aux_ipod = 1
                print('AUX или iPod: есть')

            if 'Bluetooth' in item:
                bluetooth = 1
                print('Bluetooth: есть')

            if 'CD или MP3' in item:
                cd_mp3 = 1
                print('CD или MP3: есть')

            if 'USB' in item:
                usb = 1
                print('USB: есть')

            if 'мультимедийный экран' in item:
                multimedia_monitor = 1
                print('Мультимедийный экран: есть')

            if 'штатная навигация' in item:
                factory_navigation = 1
                print('Штатная навигация: есть')
    else:
        multimedia = 0
        print('Опции мультимедиа: отсутствуют')

    # Разбираемся с функциями климата
    faras = faras[0].text
    parts = faras.split('\n')
    # print(parts)
    ksenon = np.NaN
    antifog = np.NaN
    diods = np.NaN

    if len(parts) > 1:  # если есть только заголовок - 1 элемент, то не нужен цикл
        faras = 1  # в датафрейм добавляем 1 и начинаем цикл
        print('Опции фар: присутствуют')

        for item in parts:
            if 'ксеноновые' in item:
                ksenon = 1
                print('Фары ксеноновые: есть')

            if 'противотуманные' in item:
                antifog = 1
                print('Фары противотуманные: есть')

            if 'светодиодные' in item:
                diods = 1
                print('Фары светодиодные: есть')
    else:
        faras = 0
        print('Опции фар: отсутствуют')

    # Готовим список значений для добавления в датафрейм
    row_values = [mark, model, seats, year, place, belka, baks, kpp_type, engine_volume, fuel_type, mileage, car_type, car_drive_type, 
              car_color, engine_power, fuel_consumption, exterior, disks, reiling, farkop, security, abs, esp, immobilaizer, antibuks,
              alarm, pillows, front, side, back, interior, vehicle_interior_material, vehicle_interior_color, panorama_roof, 
              car_sunroof, sevenseats_version, helpers, rain_sensor,
              backview_camera, parktroniks, mirror_deathzones_control, comfort, engine_autostart, cruise_control, 
              mediacontrol_from_steering_wheel, electrically_adjustable_seats,
              front_electric_window_regulator, back_electric_window_regulator, heaters, seats_heating, windshield_heating, 
              mirrors_heating, steering_wheel_heating, heater, climat, climat_control, condition, multimedia, aux_ipod, bluetooth, 
              cd_mp3, multimedia_monitor, factory_navigation, faras, ksenon, antifog, diods
              ]

    # Добавляем новую строку
    # df = df.append(pd.Series(row_values, index=df.columns), ignore_index=True)

    print('-------------------------------------------------------------')
    return(row_values)
    print('=============================================================')

In [12]:
# Вызываем лютый комбайн 


# Создаем список имен колонок
column_names = ['Марка', 'Модель', 'Количество мест', 'Год', 'Место размещения объявления', 'Стоимость BLR', 'Стоимость USD', 
                'Тип коробки передач', 'Объем двигателя', 'Тип топлива', 'Пробег, км', 'Тип автомобиля', 'Тип привода', 
                'Цвет автомобиля', 'Мощность двигателя, л/с', 'Расход топлива, л/100 км', 'Дополнительные элементы экстерьера', 
                'Диски', 'Рейлинги', 'Фаркоп', 'Системы безопасности', 'ABS', 'ESP', 'Иммобилайзер', 'Антипробуксовочная система', 
                'Сигнализация', 'Подушки безопасности', 'Передние подушки', 'Боковые подушки', 'Задние подушки', 'Параметры интерьера', 
                'Материал интерьера', 'Цвет интерьера', 'Панорамная крыша', 'Люк', '7 местная версия',  'Системы помощи',
                'Датчик дождя', 'Камера заднего вида',
                'Парктроники', 'Контроль мертвых зон на зеркалах', 'Дополнительные функции комфорта', 'Автозапуск двигателя', 
                'Круиз-контроль', 'Управление мультимедиа с руля', 
                'Электрорегулировка сидений', 'Передние электро-стеклоподъёмники', 'Задние электро-стеклоподъёмники',
                'Функции обогрева', 'Обогрев сидений', 'Обогрев лобового стекла', 'Обогрев зеркал', 'Обогрев руля', 
                'Автономный отопитель', 'Функции климата', 'Климат-контроль', 'Кондиционер', 'Опции мультимедиа', 'AUX или iPod',
                'Bluetooth', 'CD или MP3', 'Мультимедийный экран', 'Штатная навигация', 'Опции фар', 'Фары ксеноновые',
                'Фары противотуманные', 'Фары светодиодные']

# Создаем список значений для строки
row_values = [mark, model, seats, year, place, belka, baks, kpp_type, engine_volume, fuel_type, mileage, car_type, car_drive_type, 
              car_color, engine_power, fuel_consumption, exterior, disks, reiling, farkop, security, abs, esp, immobilaizer, antibuks,
              alarm, pillows, front, side, back, interior, vehicle_interior_material, vehicle_interior_color, panorama_roof, 
              car_sunroof, sevenseats_version, helpers, rain_sensor,
              backview_camera, parktroniks, mirror_deathzones_control, comfort, engine_autostart, cruise_control, 
              mediacontrol_from_steering_wheel, electrically_adjustable_seats,
              front_electric_window_regulator, back_electric_window_regulator, heaters, seats_heating, windshield_heating, 
              mirrors_heating, steering_wheel_heating, heater, climat, climat_control, condition, multimedia, aux_ipod, bluetooth, 
              cd_mp3, multimedia_monitor, factory_navigation, faras, ksenon, antifog, diods
              ]

# Создаем DataFrame с одной строкой
df = pd.DataFrame([row_values], columns=column_names)
df

,Марка,Модель,Количество мест,Год,Место размещения объявления,Стоимость BLR,Стоимость USD,Тип коробки передач,Объем двигателя,Тип топлива,...,Опции мультимедиа,AUX или iPod,Bluetooth,CD или MP3,Мультимедийный экран,Штатная навигация,Опции фар,Фары ксеноновые,Фары противотуманные,Фары светодиодные
0,bmw,x5,5,2019,в Барановичах,202175,62500,автомат,3.0,дизель,...,1,1,1,1,1,1,1,1,1,1